name: build

on:
  push:
    branches:
      - release
      - prerelease
      - test
jobs:
  build-debian:
    strategy:
      matrix:
        tag: [buster]
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: |
        docker build -f deployment/Dockerfile.debian -t builddeb --build-arg TAG=${{ matrix.tag }} deployment
        docker run -v $(pwd)/deployment/dist:/dist -v $(pwd):/jellyfin -e TAG=${{ matrix.tag }} builddeb
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: debian-${{ matrix.tag }}
        path: ${{ github.workspace }}/deployment/dist/*
